//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.RefinementsEcore
{
    
    
    /// <summary>
    /// The default implementation of the EOperation class
    /// </summary>
    [XmlNamespaceAttribute("http://www.transformation-tool-contest.eu/2017/LiveContest/RefinementsEcore")]
    [XmlNamespacePrefixAttribute("ecoreR")]
    [ModelRepresentationClassAttribute("http://www.transformation-tool-contest.eu/2017/LiveContest/RefinementsEcore#//EOp" +
        "eration")]
    [DebuggerDisplayAttribute("EOperation {Name}")]
    public partial class EOperation : ETypedElement, IEOperation, IModelElement
    {
        
        private static Lazy<ITypedElement> _eContainingClassReference = new Lazy<ITypedElement>(RetrieveEContainingClassReference);
        
        private static Lazy<ITypedElement> _eParametersReference = new Lazy<ITypedElement>(RetrieveEParametersReference);
        
        /// <summary>
        /// The backing field for the EParameters property
        /// </summary>
        private EOperationEParametersCollection _eParameters;
        
        private static Lazy<ITypedElement> _eExceptionsReference = new Lazy<ITypedElement>(RetrieveEExceptionsReference);
        
        /// <summary>
        /// The backing field for the EExceptions property
        /// </summary>
        private ObservableAssociationOrderedSet<IEClassifier> _eExceptions;
        
        private static IClass _classInstance;
        
        public EOperation()
        {
            this._eParameters = new EOperationEParametersCollection(this);
            this._eParameters.CollectionChanging += this.EParametersCollectionChanging;
            this._eParameters.CollectionChanged += this.EParametersCollectionChanged;
            this._eExceptions = new ObservableAssociationOrderedSet<IEClassifier>();
            this._eExceptions.CollectionChanging += this.EExceptionsCollectionChanging;
            this._eExceptions.CollectionChanged += this.EExceptionsCollectionChanged;
        }
        
        /// <summary>
        /// The eContainingClass property
        /// </summary>
        [XmlElementNameAttribute("eContainingClass")]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("eOperations")]
        public IEClass EContainingClass
        {
            get
            {
                return ModelHelper.CastAs<IEClass>(this.Parent);
            }
            set
            {
                this.Parent = value;
            }
        }
        
        /// <summary>
        /// The eParameters property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("eParameters")]
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        [XmlOppositeAttribute("eOperation")]
        [ConstantAttribute()]
        public IOrderedSetExpression<IEParameter> EParameters
        {
            get
            {
                return this._eParameters;
            }
        }
        
        /// <summary>
        /// The eExceptions property
        /// </summary>
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Content)]
        [XmlElementNameAttribute("eExceptions")]
        [XmlAttributeAttribute(true)]
        [ConstantAttribute()]
        public IOrderedSetExpression<IEClassifier> EExceptions
        {
            get
            {
                return this._eExceptions;
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new EOperationChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new EOperationReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.transformation-tool-contest.eu/2017/LiveContest/RefinementsEcore#//EOp" +
                            "eration")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the EContainingClass property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> EContainingClassChanging;
        
        /// <summary>
        /// Gets fired when the EContainingClass property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> EContainingClassChanged;
        
        private static ITypedElement RetrieveEContainingClassReference()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.RefinementsEcore.EOperation.ClassInstance)).Resolve("eContainingClass")));
        }
        
        /// <summary>
        /// Raises the EContainingClassChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnEContainingClassChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.EContainingClassChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element is about to change
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanging(IModelElement newParent, IModelElement oldParent)
        {
            IEClass oldEContainingClass = ModelHelper.CastAs<IEClass>(oldParent);
            IEClass newEContainingClass = ModelHelper.CastAs<IEClass>(newParent);
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldEContainingClass, newEContainingClass);
            this.OnEContainingClassChanging(e);
            this.OnPropertyChanging("EContainingClass", e, _eContainingClassReference);
        }
        
        /// <summary>
        /// Raises the EContainingClassChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnEContainingClassChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.EContainingClassChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Gets called when the parent model element of the current model element changes
        /// </summary>
        /// <param name="oldParent">The old parent model element</param>
        /// <param name="newParent">The new parent model element</param>
        protected override void OnParentChanged(IModelElement newParent, IModelElement oldParent)
        {
            IEClass oldEContainingClass = ModelHelper.CastAs<IEClass>(oldParent);
            IEClass newEContainingClass = ModelHelper.CastAs<IEClass>(newParent);
            if ((oldEContainingClass != null))
            {
                oldEContainingClass.EOperations.Remove(this);
            }
            if ((newEContainingClass != null))
            {
                newEContainingClass.EOperations.Add(this);
            }
            ValueChangedEventArgs e = new ValueChangedEventArgs(oldEContainingClass, newEContainingClass);
            this.OnEContainingClassChanged(e);
            this.OnPropertyChanged("EContainingClass", e, _eContainingClassReference);
            base.OnParentChanged(newParent, oldParent);
        }
        
        private static ITypedElement RetrieveEParametersReference()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.RefinementsEcore.EOperation.ClassInstance)).Resolve("eParameters")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the EParameters property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void EParametersCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("EParameters", e, _eParametersReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the EParameters property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void EParametersCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("EParameters", e, _eParametersReference);
        }
        
        private static ITypedElement RetrieveEExceptionsReference()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.RefinementsEcore.EOperation.ClassInstance)).Resolve("eExceptions")));
        }
        
        /// <summary>
        /// Forwards CollectionChanging notifications for the EExceptions property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void EExceptionsCollectionChanging(object sender, NotifyCollectionChangingEventArgs e)
        {
            this.OnCollectionChanging("EExceptions", e, _eExceptionsReference);
        }
        
        /// <summary>
        /// Forwards CollectionChanged notifications for the EExceptions property to the parent model element
        /// </summary>
        /// <param name="sender">The collection that raised the change</param>
        /// <param name="e">The original event data</param>
        private void EExceptionsCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            this.OnCollectionChanged("EExceptions", e, _eExceptionsReference);
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            int eParametersIndex = ModelHelper.IndexOfReference(this.EParameters, element);
            if ((eParametersIndex != -1))
            {
                return ModelHelper.CreatePath("eParameters", eParametersIndex);
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "EPARAMETERS"))
            {
                if ((index < this.EParameters.Count))
                {
                    return this.EParameters[index];
                }
                else
                {
                    return null;
                }
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Gets the Model element collection for the given feature
        /// </summary>
        /// <returns>A non-generic list of elements</returns>
        /// <param name="feature">The requested feature</param>
        protected override System.Collections.IList GetCollectionForFeature(string feature)
        {
            if ((feature == "EPARAMETERS"))
            {
                return this._eParameters;
            }
            if ((feature == "EEXCEPTIONS"))
            {
                return this._eExceptions;
            }
            return base.GetCollectionForFeature(feature);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "ECONTAININGCLASS"))
            {
                this.EContainingClass = ((IEClass)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "EContainingClass"))
            {
                return new EContainingClassProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "EContainingClass"))
            {
                return new EContainingClassProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the property name for the given container
        /// </summary>
        /// <returns>The name of the respective container reference</returns>
        /// <param name="container">The container object</param>
        protected override string GetCompositionName(object container)
        {
            if ((container == this._eParameters))
            {
                return "eParameters";
            }
            return base.GetCompositionName(container);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("http://www.transformation-tool-contest.eu/2017/LiveContest/RefinementsEcore#//EOp" +
                        "eration")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the EOperation class
        /// </summary>
        public class EOperationChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private EOperation _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public EOperationChildrenCollection(EOperation parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    count = (count + this._parent.EParameters.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.EParameters.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.EParameters.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                IEParameter eParametersCasted = item.As<IEParameter>();
                if ((eParametersCasted != null))
                {
                    this._parent.EParameters.Add(eParametersCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.EParameters.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if (this._parent.EParameters.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                IEnumerator<IModelElement> eParametersEnumerator = this._parent.EParameters.GetEnumerator();
                try
                {
                    for (
                    ; eParametersEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = eParametersEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    eParametersEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                IEParameter eParameterItem = item.As<IEParameter>();
                if (((eParameterItem != null) 
                            && this._parent.EParameters.Remove(eParameterItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.EParameters).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the EOperation class
        /// </summary>
        public class EOperationReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private EOperation _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public EOperationReferencedElementsCollection(EOperation parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.EContainingClass != null))
                    {
                        count = (count + 1);
                    }
                    count = (count + this._parent.EParameters.Count);
                    count = (count + this._parent.EExceptions.Count);
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.EContainingClassChanged += this.PropagateValueChanges;
                this._parent.EParameters.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
                this._parent.EExceptions.AsNotifiable().CollectionChanged += this.PropagateCollectionChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.EContainingClassChanged -= this.PropagateValueChanges;
                this._parent.EParameters.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
                this._parent.EExceptions.AsNotifiable().CollectionChanged -= this.PropagateCollectionChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.EContainingClass == null))
                {
                    IEClass eContainingClassCasted = item.As<IEClass>();
                    if ((eContainingClassCasted != null))
                    {
                        this._parent.EContainingClass = eContainingClassCasted;
                        return;
                    }
                }
                IEParameter eParametersCasted = item.As<IEParameter>();
                if ((eParametersCasted != null))
                {
                    this._parent.EParameters.Add(eParametersCasted);
                }
                IEClassifier eExceptionsCasted = item.As<IEClassifier>();
                if ((eExceptionsCasted != null))
                {
                    this._parent.EExceptions.Add(eExceptionsCasted);
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.EContainingClass = null;
                this._parent.EParameters.Clear();
                this._parent.EExceptions.Clear();
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.EContainingClass))
                {
                    return true;
                }
                if (this._parent.EParameters.Contains(item))
                {
                    return true;
                }
                if (this._parent.EExceptions.Contains(item))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.EContainingClass != null))
                {
                    array[arrayIndex] = this._parent.EContainingClass;
                    arrayIndex = (arrayIndex + 1);
                }
                IEnumerator<IModelElement> eParametersEnumerator = this._parent.EParameters.GetEnumerator();
                try
                {
                    for (
                    ; eParametersEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = eParametersEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    eParametersEnumerator.Dispose();
                }
                IEnumerator<IModelElement> eExceptionsEnumerator = this._parent.EExceptions.GetEnumerator();
                try
                {
                    for (
                    ; eExceptionsEnumerator.MoveNext(); 
                    )
                    {
                        array[arrayIndex] = eExceptionsEnumerator.Current;
                        arrayIndex = (arrayIndex + 1);
                    }
                }
                finally
                {
                    eExceptionsEnumerator.Dispose();
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.EContainingClass == item))
                {
                    this._parent.EContainingClass = null;
                    return true;
                }
                IEParameter eParameterItem = item.As<IEParameter>();
                if (((eParameterItem != null) 
                            && this._parent.EParameters.Remove(eParameterItem)))
                {
                    return true;
                }
                IEClassifier eClassifierItem = item.As<IEClassifier>();
                if (((eClassifierItem != null) 
                            && this._parent.EExceptions.Remove(eClassifierItem)))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.EContainingClass).Concat(this._parent.EParameters).Concat(this._parent.EExceptions).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the eContainingClass property
        /// </summary>
        private sealed class EContainingClassProxy : ModelPropertyChange<IEOperation, IEClass>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public EContainingClassProxy(IEOperation modelElement) : 
                    base(modelElement, "eContainingClass")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IEClass Value
            {
                get
                {
                    return this.ModelElement.EContainingClass;
                }
                set
                {
                    this.ModelElement.EContainingClass = value;
                }
            }
        }
    }
}

