//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.RefinementsEcore
{
    
    
    /// <summary>
    /// The public interface for EAnnotation
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(EAnnotation))]
    [XmlDefaultImplementationTypeAttribute(typeof(EAnnotation))]
    public interface IEAnnotation : IModelElement, IEModelElement
    {
        
        /// <summary>
        /// The source property
        /// </summary>
        string Source
        {
            get;
            set;
        }
        
        /// <summary>
        /// The eModelElement property
        /// </summary>
        IEModelElement EModelElement
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Source property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanging;
        
        /// <summary>
        /// Gets fired when the Source property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> SourceChanged;
        
        /// <summary>
        /// Gets fired before the EModelElement property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EModelElementChanging;
        
        /// <summary>
        /// Gets fired when the EModelElement property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> EModelElementChanged;
    }
}

