//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.SimpleCodeDOM
{
    
    
    /// <summary>
    /// The default implementation of the BinaryExpression class
    /// </summary>
    [XmlNamespaceAttribute("http://www.transformation-tool-contest.eu/2017/LiveContest/SimpleCodeDOM")]
    [XmlNamespacePrefixAttribute("codeDom")]
    [ModelRepresentationClassAttribute("http://www.transformation-tool-contest.eu/2017/LiveContest/SimpleCodeDOM#//Binary" +
        "Expression")]
    public partial class BinaryExpression : Expression, IBinaryExpression, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Operator property
        /// </summary>
        private BinaryOperator _operator;
        
        private static Lazy<ITypedElement> _operatorAttribute = new Lazy<ITypedElement>(RetrieveOperatorAttribute);
        
        private static Lazy<ITypedElement> _leftOperandReference = new Lazy<ITypedElement>(RetrieveLeftOperandReference);
        
        /// <summary>
        /// The backing field for the LeftOperand property
        /// </summary>
        private IExpression _leftOperand;
        
        private static Lazy<ITypedElement> _rightOperandReference = new Lazy<ITypedElement>(RetrieveRightOperandReference);
        
        /// <summary>
        /// The backing field for the RightOperand property
        /// </summary>
        private IExpression _rightOperand;
        
        private static NMF.Models.Meta.IClass _classInstance;
        
        /// <summary>
        /// The Operator property
        /// </summary>
        [XmlAttributeAttribute(true)]
        public BinaryOperator Operator
        {
            get
            {
                return this._operator;
            }
            set
            {
                if ((this._operator != value))
                {
                    BinaryOperator old = this._operator;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnOperatorChanging(e);
                    this.OnPropertyChanging("Operator", e, _operatorAttribute);
                    this._operator = value;
                    this.OnOperatorChanged(e);
                    this.OnPropertyChanged("Operator", e, _operatorAttribute);
                }
            }
        }
        
        /// <summary>
        /// The LeftOperand property
        /// </summary>
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        public IExpression LeftOperand
        {
            get
            {
                return this._leftOperand;
            }
            set
            {
                if ((this._leftOperand != value))
                {
                    IExpression old = this._leftOperand;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnLeftOperandChanging(e);
                    this.OnPropertyChanging("LeftOperand", e, _leftOperandReference);
                    this._leftOperand = value;
                    if ((old != null))
                    {
                        old.Parent = null;
                        old.ParentChanged -= this.OnResetLeftOperand;
                    }
                    if ((value != null))
                    {
                        value.Parent = this;
                        value.ParentChanged += this.OnResetLeftOperand;
                    }
                    this.OnLeftOperandChanged(e);
                    this.OnPropertyChanged("LeftOperand", e, _leftOperandReference);
                }
            }
        }
        
        /// <summary>
        /// The RightOperand property
        /// </summary>
        [XmlAttributeAttribute(false)]
        [ContainmentAttribute()]
        public IExpression RightOperand
        {
            get
            {
                return this._rightOperand;
            }
            set
            {
                if ((this._rightOperand != value))
                {
                    IExpression old = this._rightOperand;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnRightOperandChanging(e);
                    this.OnPropertyChanging("RightOperand", e, _rightOperandReference);
                    this._rightOperand = value;
                    if ((old != null))
                    {
                        old.Parent = null;
                        old.ParentChanged -= this.OnResetRightOperand;
                    }
                    if ((value != null))
                    {
                        value.Parent = this;
                        value.ParentChanged += this.OnResetRightOperand;
                    }
                    this.OnRightOperandChanged(e);
                    this.OnPropertyChanged("RightOperand", e, _rightOperandReference);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new BinaryExpressionChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the referenced model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> ReferencedElements
        {
            get
            {
                return base.ReferencedElements.Concat(new BinaryExpressionReferencedElementsCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static NMF.Models.Meta.IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://www.transformation-tool-contest.eu/2017/LiveContest/SimpleCodeDOM#//Binary" +
                            "Expression")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Operator property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> OperatorChanging;
        
        /// <summary>
        /// Gets fired when the Operator property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> OperatorChanged;
        
        /// <summary>
        /// Gets fired before the LeftOperand property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> LeftOperandChanging;
        
        /// <summary>
        /// Gets fired when the LeftOperand property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> LeftOperandChanged;
        
        /// <summary>
        /// Gets fired before the RightOperand property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> RightOperandChanging;
        
        /// <summary>
        /// Gets fired when the RightOperand property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> RightOperandChanged;
        
        private static ITypedElement RetrieveOperatorAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.SimpleCodeDOM.BinaryExpression.ClassInstance)).Resolve("Operator")));
        }
        
        /// <summary>
        /// Raises the OperatorChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnOperatorChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.OperatorChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the OperatorChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnOperatorChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.OperatorChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveLeftOperandReference()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.SimpleCodeDOM.BinaryExpression.ClassInstance)).Resolve("LeftOperand")));
        }
        
        /// <summary>
        /// Raises the LeftOperandChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnLeftOperandChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.LeftOperandChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the LeftOperandChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnLeftOperandChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.LeftOperandChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the LeftOperand property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetLeftOperand(object sender, System.EventArgs eventArgs)
        {
            this.LeftOperand = null;
        }
        
        private static ITypedElement RetrieveRightOperandReference()
        {
            return ((ITypedElement)(((ModelElement)(TTC2017.LiveContest.SimpleCodeDOM.BinaryExpression.ClassInstance)).Resolve("RightOperand")));
        }
        
        /// <summary>
        /// Raises the RightOperandChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnRightOperandChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.RightOperandChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the RightOperandChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnRightOperandChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.RightOperandChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Handles the event that the RightOperand property must reset
        /// </summary>
        /// <param name="sender">The object that sent this reset request</param>
        /// <param name="eventArgs">The event data for the reset event</param>
        private void OnResetRightOperand(object sender, System.EventArgs eventArgs)
        {
            this.RightOperand = null;
        }
        
        /// <summary>
        /// Gets the relative URI fragment for the given child model element
        /// </summary>
        /// <returns>A fragment of the relative URI</returns>
        /// <param name="element">The element that should be looked for</param>
        protected override string GetRelativePathForNonIdentifiedChild(IModelElement element)
        {
            if ((element == this.LeftOperand))
            {
                return ModelHelper.CreatePath("LeftOperand");
            }
            if ((element == this.RightOperand))
            {
                return ModelHelper.CreatePath("RightOperand");
            }
            return base.GetRelativePathForNonIdentifiedChild(element);
        }
        
        /// <summary>
        /// Resolves the given URI to a child model element
        /// </summary>
        /// <returns>The model element or null if it could not be found</returns>
        /// <param name="reference">The requested reference name</param>
        /// <param name="index">The index of this reference</param>
        protected override IModelElement GetModelElementForReference(string reference, int index)
        {
            if ((reference == "LEFTOPERAND"))
            {
                return this.LeftOperand;
            }
            if ((reference == "RIGHTOPERAND"))
            {
                return this.RightOperand;
            }
            return base.GetModelElementForReference(reference, index);
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "OPERATOR"))
            {
                return this.Operator;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "LEFTOPERAND"))
            {
                this.LeftOperand = ((IExpression)(value));
                return;
            }
            if ((feature == "RIGHTOPERAND"))
            {
                this.RightOperand = ((IExpression)(value));
                return;
            }
            if ((feature == "OPERATOR"))
            {
                this.Operator = ((BinaryOperator)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "LeftOperand"))
            {
                return new LeftOperandProxy(this);
            }
            if ((attribute == "RightOperand"))
            {
                return new RightOperandProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the property expression for the given reference
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="reference">The requested reference in upper case</param>
        protected override NMF.Expressions.INotifyExpression<NMF.Models.IModelElement> GetExpressionForReference(string reference)
        {
            if ((reference == "LeftOperand"))
            {
                return new LeftOperandProxy(this);
            }
            if ((reference == "RightOperand"))
            {
                return new RightOperandProxy(this);
            }
            return base.GetExpressionForReference(reference);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override NMF.Models.Meta.IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((NMF.Models.Meta.IClass)(MetaRepository.Instance.Resolve("http://www.transformation-tool-contest.eu/2017/LiveContest/SimpleCodeDOM#//Binary" +
                        "Expression")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the BinaryExpression class
        /// </summary>
        public class BinaryExpressionChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private BinaryExpression _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BinaryExpressionChildrenCollection(BinaryExpression parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.LeftOperand != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.RightOperand != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.LeftOperandChanged += this.PropagateValueChanges;
                this._parent.RightOperandChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.LeftOperandChanged -= this.PropagateValueChanges;
                this._parent.RightOperandChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.LeftOperand == null))
                {
                    IExpression leftOperandCasted = item.As<IExpression>();
                    if ((leftOperandCasted != null))
                    {
                        this._parent.LeftOperand = leftOperandCasted;
                        return;
                    }
                }
                if ((this._parent.RightOperand == null))
                {
                    IExpression rightOperandCasted = item.As<IExpression>();
                    if ((rightOperandCasted != null))
                    {
                        this._parent.RightOperand = rightOperandCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.LeftOperand = null;
                this._parent.RightOperand = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.LeftOperand))
                {
                    return true;
                }
                if ((item == this._parent.RightOperand))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.LeftOperand != null))
                {
                    array[arrayIndex] = this._parent.LeftOperand;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.RightOperand != null))
                {
                    array[arrayIndex] = this._parent.RightOperand;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.LeftOperand == item))
                {
                    this._parent.LeftOperand = null;
                    return true;
                }
                if ((this._parent.RightOperand == item))
                {
                    this._parent.RightOperand = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.LeftOperand).Concat(this._parent.RightOperand).GetEnumerator();
            }
        }
        
        /// <summary>
        /// The collection class to to represent the children of the BinaryExpression class
        /// </summary>
        public class BinaryExpressionReferencedElementsCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private BinaryExpression _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public BinaryExpressionReferencedElementsCollection(BinaryExpression parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    if ((this._parent.LeftOperand != null))
                    {
                        count = (count + 1);
                    }
                    if ((this._parent.RightOperand != null))
                    {
                        count = (count + 1);
                    }
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
                this._parent.LeftOperandChanged += this.PropagateValueChanges;
                this._parent.RightOperandChanged += this.PropagateValueChanges;
            }
            
            protected override void DetachCore()
            {
                this._parent.LeftOperandChanged -= this.PropagateValueChanges;
                this._parent.RightOperandChanged -= this.PropagateValueChanges;
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
                if ((this._parent.LeftOperand == null))
                {
                    IExpression leftOperandCasted = item.As<IExpression>();
                    if ((leftOperandCasted != null))
                    {
                        this._parent.LeftOperand = leftOperandCasted;
                        return;
                    }
                }
                if ((this._parent.RightOperand == null))
                {
                    IExpression rightOperandCasted = item.As<IExpression>();
                    if ((rightOperandCasted != null))
                    {
                        this._parent.RightOperand = rightOperandCasted;
                        return;
                    }
                }
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
                this._parent.LeftOperand = null;
                this._parent.RightOperand = null;
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                if ((item == this._parent.LeftOperand))
                {
                    return true;
                }
                if ((item == this._parent.RightOperand))
                {
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
                if ((this._parent.LeftOperand != null))
                {
                    array[arrayIndex] = this._parent.LeftOperand;
                    arrayIndex = (arrayIndex + 1);
                }
                if ((this._parent.RightOperand != null))
                {
                    array[arrayIndex] = this._parent.RightOperand;
                    arrayIndex = (arrayIndex + 1);
                }
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                if ((this._parent.LeftOperand == item))
                {
                    this._parent.LeftOperand = null;
                    return true;
                }
                if ((this._parent.RightOperand == item))
                {
                    this._parent.RightOperand = null;
                    return true;
                }
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().Concat(this._parent.LeftOperand).Concat(this._parent.RightOperand).GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the Operator property
        /// </summary>
        private sealed class OperatorProxy : ModelPropertyChange<IBinaryExpression, BinaryOperator>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public OperatorProxy(IBinaryExpression modelElement) : 
                    base(modelElement, "Operator")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override BinaryOperator Value
            {
                get
                {
                    return this.ModelElement.Operator;
                }
                set
                {
                    this.ModelElement.Operator = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the LeftOperand property
        /// </summary>
        private sealed class LeftOperandProxy : ModelPropertyChange<IBinaryExpression, IExpression>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public LeftOperandProxy(IBinaryExpression modelElement) : 
                    base(modelElement, "LeftOperand")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IExpression Value
            {
                get
                {
                    return this.ModelElement.LeftOperand;
                }
                set
                {
                    this.ModelElement.LeftOperand = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the RightOperand property
        /// </summary>
        private sealed class RightOperandProxy : ModelPropertyChange<IBinaryExpression, IExpression>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public RightOperandProxy(IBinaryExpression modelElement) : 
                    base(modelElement, "RightOperand")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override IExpression Value
            {
                get
                {
                    return this.ModelElement.RightOperand;
                }
                set
                {
                    this.ModelElement.RightOperand = value;
                }
            }
        }
    }
}

