//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.SimpleCodeDOM
{
    
    
    /// <summary>
    /// The public interface for BinaryExpression
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(BinaryExpression))]
    [XmlDefaultImplementationTypeAttribute(typeof(BinaryExpression))]
    public interface IBinaryExpression : IModelElement, IExpression
    {
        
        /// <summary>
        /// The Operator property
        /// </summary>
        BinaryOperator Operator
        {
            get;
            set;
        }
        
        /// <summary>
        /// The LeftOperand property
        /// </summary>
        IExpression LeftOperand
        {
            get;
            set;
        }
        
        /// <summary>
        /// The RightOperand property
        /// </summary>
        IExpression RightOperand
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Operator property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanging;
        
        /// <summary>
        /// Gets fired when the Operator property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> OperatorChanged;
        
        /// <summary>
        /// Gets fired before the LeftOperand property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LeftOperandChanging;
        
        /// <summary>
        /// Gets fired when the LeftOperand property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> LeftOperandChanged;
        
        /// <summary>
        /// Gets fired before the RightOperand property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RightOperandChanging;
        
        /// <summary>
        /// Gets fired when the RightOperand property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> RightOperandChanged;
    }
}

