//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.SimpleCodeDOM
{
    
    
    /// <summary>
    /// The public interface for Class
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Class))]
    [XmlDefaultImplementationTypeAttribute(typeof(Class))]
    public interface IClass : IModelElement
    {
        
        /// <summary>
        /// The Name property
        /// </summary>
        string Name
        {
            get;
            set;
        }
        
        /// <summary>
        /// The IsInterface property
        /// </summary>
        bool IsInterface
        {
            get;
            set;
        }
        
        /// <summary>
        /// The Members property
        /// </summary>
        IOrderedSetExpression<IMember> Members
        {
            get;
        }
        
        /// <summary>
        /// The BaseTypes property
        /// </summary>
        IOrderedSetExpression<ITypeReference> BaseTypes
        {
            get;
        }
        
        /// <summary>
        /// Gets fired before the Name property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NameChanging;
        
        /// <summary>
        /// Gets fired when the Name property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> NameChanged;
        
        /// <summary>
        /// Gets fired before the IsInterface property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsInterfaceChanging;
        
        /// <summary>
        /// Gets fired when the IsInterface property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> IsInterfaceChanged;
    }
}

