//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.SimpleCodeDOM
{
    
    
    /// <summary>
    /// The public interface for ConditionalExpression
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(ConditionalExpression))]
    [XmlDefaultImplementationTypeAttribute(typeof(ConditionalExpression))]
    public interface IConditionalExpression : IModelElement, IExpression
    {
        
        /// <summary>
        /// The Test property
        /// </summary>
        IExpression Test
        {
            get;
            set;
        }
        
        /// <summary>
        /// The TrueExpression property
        /// </summary>
        IExpression TrueExpression
        {
            get;
            set;
        }
        
        /// <summary>
        /// The FalseExpression property
        /// </summary>
        IExpression FalseExpression
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Test property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TestChanging;
        
        /// <summary>
        /// Gets fired when the Test property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TestChanged;
        
        /// <summary>
        /// Gets fired before the TrueExpression property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TrueExpressionChanging;
        
        /// <summary>
        /// Gets fired when the TrueExpression property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TrueExpressionChanged;
        
        /// <summary>
        /// Gets fired before the FalseExpression property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FalseExpressionChanging;
        
        /// <summary>
        /// Gets fired when the FalseExpression property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FalseExpressionChanged;
    }
}

