//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2017.LiveContest.SimpleCodeDOM
{
    
    
    /// <summary>
    /// The public interface for FieldReferenceExpression
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(FieldReferenceExpression))]
    [XmlDefaultImplementationTypeAttribute(typeof(FieldReferenceExpression))]
    public interface IFieldReferenceExpression : IModelElement, IExpression
    {
        
        /// <summary>
        /// The FieldName property
        /// </summary>
        string FieldName
        {
            get;
            set;
        }
        
        /// <summary>
        /// The TargetObject property
        /// </summary>
        IExpression TargetObject
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the FieldName property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldNameChanging;
        
        /// <summary>
        /// Gets fired when the FieldName property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> FieldNameChanged;
        
        /// <summary>
        /// Gets fired before the TargetObject property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TargetObjectChanging;
        
        /// <summary>
        /// Gets fired when the TargetObject property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> TargetObjectChanged;
    }
}

